{% set version = "0.12.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-datawizard
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/datawizard_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/datawizard/datawizard_{{ version }}.tar.gz
  sha256: fee36520440131596394878eb19f295609ef5d7997a3a5614c059f2a8d2be081

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-insight >=0.14.1
  run:
    - r-base
    - r-insight >=0.14.1

test:
  commands:
    - $R -e "library('datawizard')"           # [not win]
    - "\"%R%\" -e \"library('datawizard')\""  # [win]

about:
  home: https://easystats.github.io/datawizard/
  license: GPL-3.0-only
  summary: A lightweight package to easily manipulate, clean, transform, and prepare your data for analysis. It also forms the data wrangling backend for the packages in the 'easystats' ecosystem.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
